In [41]:
# Imports
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [42]:
# Read raw data
data = pd.read_csv("C:\\Users\\bkb3\\Documents\\US_Accidents_March23.csv")

In [43]:
# Subset to MD based data only
df = data[data["State"]=='MD']

In [44]:
# View data, remove duplicate rows
df.head()
df = df.drop_duplicates()

In [45]:
# Check all unique values for all columns
for col in df.columns:
    print(df[col].value_counts(sort=True))

ID
A-7777383    1
A-7774726    1
A-7774727    1
A-7774733    1
A-7774736    1
            ..
A-228580     1
A-228630     1
A-228632     1
A-228641     1
A-228649     1
Name: count, Length: 140417, dtype: int64
Source
Source1    98441
Source2    41321
Source3      655
Name: count, dtype: int64
Severity
2    103558
3     25450
4     10892
1       517
Name: count, dtype: int64
Start_Time
2021-05-28 07:31:48    30
2022-05-18 07:05:30    22
2021-11-06 16:59:00    19
2022-04-23 18:32:30    17
2020-06-26 18:14:49    17
                       ..
2019-08-15 16:21:25     1
2019-08-15 18:25:50     1
2019-08-16 19:57:05     1
2019-08-16 19:59:23     1
2016-12-01 06:35:00     1
Name: count, Length: 117296, dtype: int64
End_Time
2022-07-15 15:23:55    10
2020-12-19 00:51:28    10
2021-02-22 12:48:14    10
2020-04-30 16:37:30     9
2021-05-28 09:11:52     9
                       ..
2019-08-15 16:50:26     1
2019-08-15 18:53:25     1
2019-08-16 20:26:17     1
2019-08-16 20:28:09     1
2016-11-30 17:02:36     1
Name: count, Length: 126300, dtype: int64
Start_Lat
38.971164    209
39.442020    193
39.379276    186
39.323437    163
39.381805    160
            ...
39.359376      1
38.820800      1
39.444149      1
38.946055      1
39.358382      1
Name: count, Length: 50355, dtype: int64
Start_Lng
-77.179063    209
-76.349358    194
-76.448280    185
-77.042068    168
-77.357155    163
             ...
-77.456250      1
-76.617760      1
-76.839600      1
-76.839730      1
-76.707176      1
Name: count, Length: 50643, dtype: int64
End_Lat
38.988969    155
38.912285    101
39.019136     92
39.466545     90
38.916780     84
            ...
38.780743      1
38.516119      1
38.516075      1
39.298519      1
39.444981      1
Name: count, Length: 35083, dtype: int64
End_Lng
-76.987615    155
-76.934168    101
-76.959084     92
-76.286576     90
-76.932640     84
             ...
-76.839730      1
-76.839600      1
-77.114742      1
-76.396974      1
-75.787693      1
Name: count, Length: 35230, dtype: int64
Distance(mi)
0.000    38190
0.010     6367
0.010      394
0.020      291
0.008      289
         ...
8.281        1
2.725        1
4.791        1
3.202        1
4.232        1
Name: count, Length: 6274, dtype: int64
Description
Incident on BRANCH AVE near BRANCH AVE Drive with caution.                                        442
Incident on CRAIN HWY near CRAIN HWY Drive with caution.                                          417
Incident on I-495 WB near I-495 Drive with caution.                                               412
Incident on I-495 EB near I-495 Drive with caution.                                               405
Incident on INDIAN HEAD HWY near INDIAN HEAD HWY Drive with caution.                              313
                                                                                                 ...
At MD-100/Exit 14 - Accident. Right lane blocked.                                                   1
Between MD-140/Reisterstown Rd/Exit 20 and Stevenson Rd/Exit 21 - Accident. Left lane blocked.      1
At College Ave - Accident. Right lane blocked.                                                      1
At MD-3/Crain Hwy - Accident. Right lane blocked.                                                   1
Accident on MD-75 Green Valley Rd at Greenhill Ct.                                                  1
Name: count, Length: 69032, dtype: int64
Street
I-95 S                 5747
I-95 N                 5662
Capital Beltway S      4052
Capital Beltway N      3224
Capital Beltway W      2892
                       ...
 Kalmia Rd                1
 Dodge Park Rd            1
 Vansants Corner Rd       1
 Scarff Rd                1
Arcadia St                1
Name: count, Length: 7621, dtype: int64
City
Baltimore                  9077
Frederick                  8031
Silver Spring              7926
Hyattsville                5723
Bethesda                   5067
                           ...
District 13                   1
District 6 Northern           1
Galesville                    1
District 1 Abingdon           1
Aberdeen Proving Ground       1
Name: count, Length: 381, dtype: int64
County
Prince George's         26791
Montgomery              22565
Baltimore County        18283
Frederick               13056
Anne Arundel            11950
Baltimore City           8768
Harford                  6802
Howard                   6134
Washington               4848
Baltimore                4091
Cecil                    2482
Charles                  2037
Queen Anne's             1999
Baltimore (City)         1448
Carroll                  1360
Talbot                   1179
Worcester                1154
Caroline                  908
Allegany                  770
Wicomico                  621
Dorchester                593
St. Mary's                544
Queen Annes               437
Garrett                   360
Prince Georges            352
Kent                      328
Calvert                   223
Somerset                  216
St Marys                  110
District Of Columbia        4
Saint Marys                 4
Name: count, dtype: int64
State
MD    140417
Name: count, dtype: int64
Zipcode
21227         3172
21224         2876
20817         2591
21230         2178
21704         2137
              ...
20832-1888       1
21901-2603       1
21229-3620       1
20743-6146       1
20743-3103       1
Name: count, Length: 10859, dtype: int64
Country
US    140417
Name: count, dtype: int64
Timezone
US/Eastern    140157
Name: count, dtype: int64
Airport_Code
KCGS    24175
KDMH    21443
KFDK    11859
KBWI    11687
KMTN     8599
KGAI     8509
KAPG     7098
KDCA     6436
KFME     6308
KADW     5665
KWBC     4735
KHGR     3677
KNAK     3361
KDMW     2917
KRSP     2012
KRJD     1588
KW29     1386
KESN     1032
KOXB      978
KCGE      900
KILG      869
KCBE      799
KDAA      746
KSBY      733
K2W6      717
KMRB      527
K2G4      330
KJYO      236
KWAL      221
KRYT      190
KNYG      183
KNHK      153
KNUI       20
KGED        1
Name: count, dtype: int64
Weather_Timestamp
2022-03-13 01:55:00    64
2021-05-28 07:58:00    34
2022-05-18 06:52:00    29
2021-02-04 14:56:00    26
2021-11-06 16:55:00    25
                       ..
2019-08-14 15:08:00     1
2019-08-14 15:23:00     1
2019-08-14 16:43:00     1
2019-08-10 09:54:00     1
2019-08-10 18:56:00     1
Name: count, Length: 70648, dtype: int64
Temperature(F)
32.0    2770
70.0    2598
73.0    2596
50.0    2568
45.0    2493
        ...
93.4       1
23.7       1
13.5       1
21.7       1
14.9       1
Name: count, Length: 523, dtype: int64
Wind_Chill(F)
 70.0    2204
 73.0    2144
 72.0    2094
 52.0    2012
 54.0    1910
         ...
 0.3        1
-4.0        1
 7.4        1
-6.9        1
 43.7       1
Name: count, Length: 517, dtype: int64
Humidity(%)
100.0    8655
93.0     6437
94.0     4928
87.0     2562
88.0     2247
         ...
10.0        9
8.0         4
9.0         3
6.0         2
7.0         1
Name: count, Length: 95, dtype: int64
Pressure(in)
30.01    2086
29.94    2068
30.04    2040
29.99    2032
30.06    1992
         ...
27.16       1
27.23       1
27.33       1
27.29       1
26.82       1
Name: count, Length: 279, dtype: int64
Visibility(mi)
10.00    88934
7.00      5695
5.00      2847
4.00      2339
3.00      2192
2.00      2161
9.00      1908
1.00      1818
8.00      1264
6.00      1222
0.50       598
0.25       430
2.50       341
0.75       300
0.20       174
1.50       148
0.80       140
1.80       111
1.20        89
0.00        63
0.12        41
0.38        37
0.10        21
0.19        19
0.63        12
0.06         8
0.88         6
1.90         5
0.60         4
1.10         4
3.50         4
1.40         3
20.00        3
2.80         3
2.20         3
10.50        3
0.90         2
2.10         2
0.40         1
1.60         1
Name: count, dtype: int64
Wind_Direction
CALM        22468
WNW          8282
North        7832
NW           7678
Calm         7425
S            6376
W            6225
NNW          5699
SSW          5230
N            4649
SW           4328
SSE          4009
SE           3657
WSW          3633
NNE          3567
NE           3257
ENE          2982
E            2773
ESE          2582
West         2152
VAR          2090
South        1600
East         1022
Variable      697
Name: count, dtype: int64
Wind_Speed(mph)
0.0      22468
5.0       8951
6.0       8888
3.0       8584
7.0       7824
         ...
117.0        1
34.5         1
41.0         1
29.9         1
110.0        1
Name: count, Length: 67, dtype: int64
Precipitation(in)
0.00    83857
0.01     2003
0.02     1029
0.03      666
0.04      547
        ...
0.70        1
0.64        1
1.11        1
0.41        1
0.66        1
Name: count, Length: 88, dtype: int64
Weather_Condition
Fair                       38856
Cloudy                     18094
Mostly Cloudy              14777
Partly Cloudy               9908
Clear                       9387
                           ...
Drizzle and Fog                2
Light Snow Shower              1
Heavy Ice Pellets              1
Showers in the Vicinity        1
Squalls / Windy                1
Name: count, Length: 71, dtype: int64
Amenity
False    139397
True       1020
Name: count, dtype: int64
Bump
False    140383
True         34
Name: count, dtype: int64
Crossing
False    131378
True       9039
Name: count, dtype: int64
Give_Way
False    140060
True        357
Name: count, dtype: int64
Junction
False    123332
True      17085
Name: count, dtype: int64
No_Exit
False    140234
True        183
Name: count, dtype: int64
Railway
False    139815
True        602
Name: count, dtype: int64
Roundabout
False    140412
True          5
Name: count, dtype: int64
Station
False    138024
True       2393
Name: count, dtype: int64
Stop
False    138903
True       1514
Name: count, dtype: int64
Traffic_Calming
False    139953
True        464
Name: count, dtype: int64
Traffic_Signal
False    124509
True      15908
Name: count, dtype: int64
Turning_Loop
False    140417
Name: count, dtype: int64
Sunrise_Sunset
Day      93834
Night    46297
Name: count, dtype: int64
Civil_Twilight
Day      100731
Night     39400
Name: count, dtype: int64
Nautical_Twilight
Day      107877
Night     32254
Name: count, dtype: int64
Astronomical_Twilight
Day      113918
Night     26213
Name: count, dtype: int64

In [46]:
# Worth keeping weather time stamp? Examine value types
print(df["Weather_Timestamp"].value_counts(sort=True))

Weather_Timestamp
2022-03-13 01:55:00    64
2021-05-28 07:58:00    34
2022-05-18 06:52:00    29
2021-02-04 14:56:00    26
2021-11-06 16:55:00    25
                       ..
2019-08-14 15:08:00     1
2019-08-14 15:23:00     1
2019-08-14 16:43:00     1
2019-08-10 09:54:00     1
2019-08-10 18:56:00     1
Name: count, Length: 70648, dtype: int64

In [47]:
# Check all values of all remaining cols
for col in df.columns:
    print(df[col].value_counts(sort=True))

ID
A-7777383    1
A-7774726    1
A-7774727    1
A-7774733    1
A-7774736    1
            ..
A-228580     1
A-228630     1
A-228632     1
A-228641     1
A-228649     1
Name: count, Length: 140417, dtype: int64
Source
Source1    98441
Source2    41321
Source3      655
Name: count, dtype: int64
Severity
2    103558
3     25450
4     10892
1       517
Name: count, dtype: int64
Start_Time
2021-05-28 07:31:48    30
2022-05-18 07:05:30    22
2021-11-06 16:59:00    19
2022-04-23 18:32:30    17
2020-06-26 18:14:49    17
                       ..
2019-08-15 16:21:25     1
2019-08-15 18:25:50     1
2019-08-16 19:57:05     1
2019-08-16 19:59:23     1
2016-12-01 06:35:00     1
Name: count, Length: 117296, dtype: int64
End_Time
2022-07-15 15:23:55    10
2020-12-19 00:51:28    10
2021-02-22 12:48:14    10
2020-04-30 16:37:30     9
2021-05-28 09:11:52     9
                       ..
2019-08-15 16:50:26     1
2019-08-15 18:53:25     1
2019-08-16 20:26:17     1
2019-08-16 20:28:09     1
2016-11-30 17:02:36     1
Name: count, Length: 126300, dtype: int64
Start_Lat
38.971164    209
39.442020    193
39.379276    186
39.323437    163
39.381805    160
            ...
39.359376      1
38.820800      1
39.444149      1
38.946055      1
39.358382      1
Name: count, Length: 50355, dtype: int64
Start_Lng
-77.179063    209
-76.349358    194
-76.448280    185
-77.042068    168
-77.357155    163
             ...
-77.456250      1
-76.617760      1
-76.839600      1
-76.839730      1
-76.707176      1
Name: count, Length: 50643, dtype: int64
End_Lat
38.988969    155
38.912285    101
39.019136     92
39.466545     90
38.916780     84
            ...
38.780743      1
38.516119      1
38.516075      1
39.298519      1
39.444981      1
Name: count, Length: 35083, dtype: int64
End_Lng
-76.987615    155
-76.934168    101
-76.959084     92
-76.286576     90
-76.932640     84
             ...
-76.839730      1
-76.839600      1
-77.114742      1
-76.396974      1
-75.787693      1
Name: count, Length: 35230, dtype: int64
Distance(mi)
0.000    38190
0.010     6367
0.010      394
0.020      291
0.008      289
         ...
8.281        1
2.725        1
4.791        1
3.202        1
4.232        1
Name: count, Length: 6274, dtype: int64
Description
Incident on BRANCH AVE near BRANCH AVE Drive with caution.                                        442
Incident on CRAIN HWY near CRAIN HWY Drive with caution.                                          417
Incident on I-495 WB near I-495 Drive with caution.                                               412
Incident on I-495 EB near I-495 Drive with caution.                                               405
Incident on INDIAN HEAD HWY near INDIAN HEAD HWY Drive with caution.                              313
                                                                                                 ...
At MD-100/Exit 14 - Accident. Right lane blocked.                                                   1
Between MD-140/Reisterstown Rd/Exit 20 and Stevenson Rd/Exit 21 - Accident. Left lane blocked.      1
At College Ave - Accident. Right lane blocked.                                                      1
At MD-3/Crain Hwy - Accident. Right lane blocked.                                                   1
Accident on MD-75 Green Valley Rd at Greenhill Ct.                                                  1
Name: count, Length: 69032, dtype: int64
Street
I-95 S                 5747
I-95 N                 5662
Capital Beltway S      4052
Capital Beltway N      3224
Capital Beltway W      2892
                       ...
 Kalmia Rd                1
 Dodge Park Rd            1
 Vansants Corner Rd       1
 Scarff Rd                1
Arcadia St                1
Name: count, Length: 7621, dtype: int64
City
Baltimore                  9077
Frederick                  8031
Silver Spring              7926
Hyattsville                5723
Bethesda                   5067
                           ...
District 13                   1
District 6 Northern           1
Galesville                    1
District 1 Abingdon           1
Aberdeen Proving Ground       1
Name: count, Length: 381, dtype: int64
County
Prince George's         26791
Montgomery              22565
Baltimore County        18283
Frederick               13056
Anne Arundel            11950
Baltimore City           8768
Harford                  6802
Howard                   6134
Washington               4848
Baltimore                4091
Cecil                    2482
Charles                  2037
Queen Anne's             1999
Baltimore (City)         1448
Carroll                  1360
Talbot                   1179
Worcester                1154
Caroline                  908
Allegany                  770
Wicomico                  621
Dorchester                593
St. Mary's                544
Queen Annes               437
Garrett                   360
Prince Georges            352
Kent                      328
Calvert                   223
Somerset                  216
St Marys                  110
District Of Columbia        4
Saint Marys                 4
Name: count, dtype: int64
State
MD    140417
Name: count, dtype: int64
Zipcode
21227         3172
21224         2876
20817         2591
21230         2178
21704         2137
              ...
20832-1888       1
21901-2603       1
21229-3620       1
20743-6146       1
20743-3103       1
Name: count, Length: 10859, dtype: int64
Country
US    140417
Name: count, dtype: int64
Timezone
US/Eastern    140157
Name: count, dtype: int64
Airport_Code
KCGS    24175
KDMH    21443
KFDK    11859
KBWI    11687
KMTN     8599
KGAI     8509
KAPG     7098
KDCA     6436
KFME     6308
KADW     5665
KWBC     4735
KHGR     3677
KNAK     3361
KDMW     2917
KRSP     2012
KRJD     1588
KW29     1386
KESN     1032
KOXB      978
KCGE      900
KILG      869
KCBE      799
KDAA      746
KSBY      733
K2W6      717
KMRB      527
K2G4      330
KJYO      236
KWAL      221
KRYT      190
KNYG      183
KNHK      153
KNUI       20
KGED        1
Name: count, dtype: int64
Weather_Timestamp
2022-03-13 01:55:00    64
2021-05-28 07:58:00    34
2022-05-18 06:52:00    29
2021-02-04 14:56:00    26
2021-11-06 16:55:00    25
                       ..
2019-08-14 15:08:00     1
2019-08-14 15:23:00     1
2019-08-14 16:43:00     1
2019-08-10 09:54:00     1
2019-08-10 18:56:00     1
Name: count, Length: 70648, dtype: int64
Temperature(F)
32.0    2770
70.0    2598
73.0    2596
50.0    2568
45.0    2493
        ...
93.4       1
23.7       1
13.5       1
21.7       1
14.9       1
Name: count, Length: 523, dtype: int64
Wind_Chill(F)
 70.0    2204
 73.0    2144
 72.0    2094
 52.0    2012
 54.0    1910
         ...
 0.3        1
-4.0        1
 7.4        1
-6.9        1
 43.7       1
Name: count, Length: 517, dtype: int64
Humidity(%)
100.0    8655
93.0     6437
94.0     4928
87.0     2562
88.0     2247
         ...
10.0        9
8.0         4
9.0         3
6.0         2
7.0         1
Name: count, Length: 95, dtype: int64
Pressure(in)
30.01    2086
29.94    2068
30.04    2040
29.99    2032
30.06    1992
         ...
27.16       1
27.23       1
27.33       1
27.29       1
26.82       1
Name: count, Length: 279, dtype: int64
Visibility(mi)
10.00    88934
7.00      5695
5.00      2847
4.00      2339
3.00      2192
2.00      2161
9.00      1908
1.00      1818
8.00      1264
6.00      1222
0.50       598
0.25       430
2.50       341
0.75       300
0.20       174
1.50       148
0.80       140
1.80       111
1.20        89
0.00        63
0.12        41
0.38        37
0.10        21
0.19        19
0.63        12
0.06         8
0.88         6
1.90         5
0.60         4
1.10         4
3.50         4
1.40         3
20.00        3
2.80         3
2.20         3
10.50        3
0.90         2
2.10         2
0.40         1
1.60         1
Name: count, dtype: int64
Wind_Direction
CALM        22468
WNW          8282
North        7832
NW           7678
Calm         7425
S            6376
W            6225
NNW          5699
SSW          5230
N            4649
SW           4328
SSE          4009
SE           3657
WSW          3633
NNE          3567
NE           3257
ENE          2982
E            2773
ESE          2582
West         2152
VAR          2090
South        1600
East         1022
Variable      697
Name: count, dtype: int64
Wind_Speed(mph)
0.0      22468
5.0       8951
6.0       8888
3.0       8584
7.0       7824
         ...
117.0        1
34.5         1
41.0         1
29.9         1
110.0        1
Name: count, Length: 67, dtype: int64
Precipitation(in)
0.00    83857
0.01     2003
0.02     1029
0.03      666
0.04      547
        ...
0.70        1
0.64        1
1.11        1
0.41        1
0.66        1
Name: count, Length: 88, dtype: int64
Weather_Condition
Fair                       38856
Cloudy                     18094
Mostly Cloudy              14777
Partly Cloudy               9908
Clear                       9387
                           ...
Drizzle and Fog                2
Light Snow Shower              1
Heavy Ice Pellets              1
Showers in the Vicinity        1
Squalls / Windy                1
Name: count, Length: 71, dtype: int64
Amenity
False    139397
True       1020
Name: count, dtype: int64
Bump
False    140383
True         34
Name: count, dtype: int64
Crossing
False    131378
True       9039
Name: count, dtype: int64
Give_Way
False    140060
True        357
Name: count, dtype: int64
Junction
False    123332
True      17085
Name: count, dtype: int64
No_Exit
False    140234
True        183
Name: count, dtype: int64
Railway
False    139815
True        602
Name: count, dtype: int64
Roundabout
False    140412
True          5
Name: count, dtype: int64
Station
False    138024
True       2393
Name: count, dtype: int64
Stop
False    138903
True       1514
Name: count, dtype: int64
Traffic_Calming
False    139953
True        464
Name: count, dtype: int64
Traffic_Signal
False    124509
True      15908
Name: count, dtype: int64
Turning_Loop
False    140417
Name: count, dtype: int64
Sunrise_Sunset
Day      93834
Night    46297
Name: count, dtype: int64
Civil_Twilight
Day      100731
Night     39400
Name: count, dtype: int64
Nautical_Twilight
Day      107877
Night     32254
Name: count, dtype: int64
Astronomical_Twilight
Day      113918
Night     26213
Name: count, dtype: int64

In [48]:
# Date/time conversion, calculate length of traffic holdup in hours/fractions of an hour
df['Start_Time'] = pd.to_datetime(df['Start_Time'],format='mixed')
df['End_Time'] = pd.to_datetime(df['End_Time'], format = 'mixed')
df

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
228546,A-228553,Source2,2,2016-11-30 11:58:01,2016-11-30 16:57:20,39.152046,-76.645584,NaN,NaN,0.010,...,False,False,False,False,False,False,Day,Day,Day,Day
228547,A-228554,Source2,3,2016-11-30 12:04:03,2016-11-30 17:02:36,39.152046,-76.645584,NaN,NaN,0.010,...,False,False,False,False,False,False,Day,Day,Day,Day
228560,A-228567,Source2,2,2016-11-30 16:54:53,2016-11-30 17:24:12,39.481083,-76.249626,NaN,NaN,0.010,...,False,False,False,False,True,False,Night,Day,Day,Day
228567,A-228574,Source2,2,2016-11-30 17:33:47,2016-11-30 18:01:49,39.158756,-76.718475,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Night,Day,Day
228573,A-228580,Source2,2,2016-11-30 17:35:33,2016-11-30 18:05:10,39.636391,-77.710457,NaN,NaN,0.010,...,False,False,False,False,True,False,Night,Night,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7727511,A-7776879,Source1,2,2019-08-22 19:48:26,2019-08-22 20:17:11,39.494560,-76.892370,39.49561,-76.89158,0.084,...,False,False,False,False,False,False,Day,Day,Day,Day
7727512,A-7776880,Source1,2,2019-08-22 19:48:26,2019-08-22 20:17:11,39.495610,-76.891580,39.49456,-76.89237,0.084,...,False,False,False,False,True,False,Day,Day,Day,Day
7727513,A-7776881,Source1,4,2019-08-22 19:57:25,2019-08-23 00:56:06,39.600500,-77.677230,39.60544,-77.73422,3.053,...,False,False,False,False,False,False,Night,Day,Day,Day
7727996,A-7777364,Source1,2,2019-08-23 08:03:29,2019-08-23 08:32:31,39.336120,-76.491730,39.33962,-76.49409,0.273,...,False,False,False,False,False,False,Day,Day,Day,Day
7728015,A-7777383,Source1,3,2019-08-23 17:03:55,2019-08-23 17:33:46,39.030140,-77.122970,39.03093,-77.12763,0.256,...,False,False,False,False,False,False,Day,Day,Day,Day

In [49]:
# Check unique values for all cols again
for col in df.columns:
    print(df[col].value_counts(sort=True))

ID
A-7777383    1
A-7774726    1
A-7774727    1
A-7774733    1
A-7774736    1
            ..
A-228580     1
A-228630     1
A-228632     1
A-228641     1
A-228649     1
Name: count, Length: 140417, dtype: int64
Source
Source1    98441
Source2    41321
Source3      655
Name: count, dtype: int64
Severity
2    103558
3     25450
4     10892
1       517
Name: count, dtype: int64
Start_Time
2021-05-28 07:31:48    34
2022-05-18 07:05:30    29
2022-04-23 18:32:30    24
2021-11-06 16:59:00    24
2022-07-15 14:05:49    22
                       ..
2019-08-15 16:21:25     1
2019-08-15 18:25:50     1
2019-08-16 19:57:05     1
2019-08-16 19:59:23     1
2016-12-01 17:58:44     1
Name: count, Length: 111577, dtype: int64
End_Time
2022-07-15 15:23:55    14
2020-12-19 00:51:28    10
2021-02-22 12:48:14    10
2021-05-28 09:11:52    10
2022-03-12 16:54:44    10
                       ..
2019-08-15 16:50:26     1
2019-08-15 18:53:25     1
2019-08-16 20:26:17     1
2019-08-16 20:28:09     1
2016-11-30 18:05:10     1
Name: count, Length: 122879, dtype: int64
Start_Lat
38.971164    209
39.442020    193
39.379276    186
39.323437    163
39.381805    160
            ...
39.359376      1
38.820800      1
39.444149      1
38.946055      1
39.358382      1
Name: count, Length: 50355, dtype: int64
Start_Lng
-77.179063    209
-76.349358    194
-76.448280    185
-77.042068    168
-77.357155    163
             ...
-77.456250      1
-76.617760      1
-76.839600      1
-76.839730      1
-76.707176      1
Name: count, Length: 50643, dtype: int64
End_Lat
38.988969    155
38.912285    101
39.019136     92
39.466545     90
38.916780     84
            ...
38.780743      1
38.516119      1
38.516075      1
39.298519      1
39.444981      1
Name: count, Length: 35083, dtype: int64
End_Lng
-76.987615    155
-76.934168    101
-76.959084     92
-76.286576     90
-76.932640     84
             ...
-76.839730      1
-76.839600      1
-77.114742      1
-76.396974      1
-75.787693      1
Name: count, Length: 35230, dtype: int64
Distance(mi)
0.000    38190
0.010     6367
0.010      394
0.020      291
0.008      289
         ...
8.281        1
2.725        1
4.791        1
3.202        1
4.232        1
Name: count, Length: 6274, dtype: int64
Description
Incident on BRANCH AVE near BRANCH AVE Drive with caution.                                        442
Incident on CRAIN HWY near CRAIN HWY Drive with caution.                                          417
Incident on I-495 WB near I-495 Drive with caution.                                               412
Incident on I-495 EB near I-495 Drive with caution.                                               405
Incident on INDIAN HEAD HWY near INDIAN HEAD HWY Drive with caution.                              313
                                                                                                 ...
At MD-100/Exit 14 - Accident. Right lane blocked.                                                   1
Between MD-140/Reisterstown Rd/Exit 20 and Stevenson Rd/Exit 21 - Accident. Left lane blocked.      1
At College Ave - Accident. Right lane blocked.                                                      1
At MD-3/Crain Hwy - Accident. Right lane blocked.                                                   1
Accident on MD-75 Green Valley Rd at Greenhill Ct.                                                  1
Name: count, Length: 69032, dtype: int64
Street
I-95 S                 5747
I-95 N                 5662
Capital Beltway S      4052
Capital Beltway N      3224
Capital Beltway W      2892
                       ...
 Kalmia Rd                1
 Dodge Park Rd            1
 Vansants Corner Rd       1
 Scarff Rd                1
Arcadia St                1
Name: count, Length: 7621, dtype: int64
City
Baltimore                  9077
Frederick                  8031
Silver Spring              7926
Hyattsville                5723
Bethesda                   5067
                           ...
District 13                   1
District 6 Northern           1
Galesville                    1
District 1 Abingdon           1
Aberdeen Proving Ground       1
Name: count, Length: 381, dtype: int64
County
Prince George's         26791
Montgomery              22565
Baltimore County        18283
Frederick               13056
Anne Arundel            11950
Baltimore City           8768
Harford                  6802
Howard                   6134
Washington               4848
Baltimore                4091
Cecil                    2482
Charles                  2037
Queen Anne's             1999
Baltimore (City)         1448
Carroll                  1360
Talbot                   1179
Worcester                1154
Caroline                  908
Allegany                  770
Wicomico                  621
Dorchester                593
St. Mary's                544
Queen Annes               437
Garrett                   360
Prince Georges            352
Kent                      328
Calvert                   223
Somerset                  216
St Marys                  110
District Of Columbia        4
Saint Marys                 4
Name: count, dtype: int64
State
MD    140417
Name: count, dtype: int64
Zipcode
21227         3172
21224         2876
20817         2591
21230         2178
21704         2137
              ...
20832-1888       1
21901-2603       1
21229-3620       1
20743-6146       1
20743-3103       1
Name: count, Length: 10859, dtype: int64
Country
US    140417
Name: count, dtype: int64
Timezone
US/Eastern    140157
Name: count, dtype: int64
Airport_Code
KCGS    24175
KDMH    21443
KFDK    11859
KBWI    11687
KMTN     8599
KGAI     8509
KAPG     7098
KDCA     6436
KFME     6308
KADW     5665
KWBC     4735
KHGR     3677
KNAK     3361
KDMW     2917
KRSP     2012
KRJD     1588
KW29     1386
KESN     1032
KOXB      978
KCGE      900
KILG      869
KCBE      799
KDAA      746
KSBY      733
K2W6      717
KMRB      527
K2G4      330
KJYO      236
KWAL      221
KRYT      190
KNYG      183
KNHK      153
KNUI       20
KGED        1
Name: count, dtype: int64
Weather_Timestamp
2022-03-13 01:55:00    64
2021-05-28 07:58:00    34
2022-05-18 06:52:00    29
2021-02-04 14:56:00    26
2021-11-06 16:55:00    25
                       ..
2019-08-14 15:08:00     1
2019-08-14 15:23:00     1
2019-08-14 16:43:00     1
2019-08-10 09:54:00     1
2019-08-10 18:56:00     1
Name: count, Length: 70648, dtype: int64
Temperature(F)
32.0    2770
70.0    2598
73.0    2596
50.0    2568
45.0    2493
        ...
93.4       1
23.7       1
13.5       1
21.7       1
14.9       1
Name: count, Length: 523, dtype: int64
Wind_Chill(F)
 70.0    2204
 73.0    2144
 72.0    2094
 52.0    2012
 54.0    1910
         ...
 0.3        1
-4.0        1
 7.4        1
-6.9        1
 43.7       1
Name: count, Length: 517, dtype: int64
Humidity(%)
100.0    8655
93.0     6437
94.0     4928
87.0     2562
88.0     2247
         ...
10.0        9
8.0         4
9.0         3
6.0         2
7.0         1
Name: count, Length: 95, dtype: int64
Pressure(in)
30.01    2086
29.94    2068
30.04    2040
29.99    2032
30.06    1992
         ...
27.16       1
27.23       1
27.33       1
27.29       1
26.82       1
Name: count, Length: 279, dtype: int64
Visibility(mi)
10.00    88934
7.00      5695
5.00      2847
4.00      2339
3.00      2192
2.00      2161
9.00      1908
1.00      1818
8.00      1264
6.00      1222
0.50       598
0.25       430
2.50       341
0.75       300
0.20       174
1.50       148
0.80       140
1.80       111
1.20        89
0.00        63
0.12        41
0.38        37
0.10        21
0.19        19
0.63        12
0.06         8
0.88         6
1.90         5
0.60         4
1.10         4
3.50         4
1.40         3
20.00        3
2.80         3
2.20         3
10.50        3
0.90         2
2.10         2
0.40         1
1.60         1
Name: count, dtype: int64
Wind_Direction
CALM        22468
WNW          8282
North        7832
NW           7678
Calm         7425
S            6376
W            6225
NNW          5699
SSW          5230
N            4649
SW           4328
SSE          4009
SE           3657
WSW          3633
NNE          3567
NE           3257
ENE          2982
E            2773
ESE          2582
West         2152
VAR          2090
South        1600
East         1022
Variable      697
Name: count, dtype: int64
Wind_Speed(mph)
0.0      22468
5.0       8951
6.0       8888
3.0       8584
7.0       7824
         ...
117.0        1
34.5         1
41.0         1
29.9         1
110.0        1
Name: count, Length: 67, dtype: int64
Precipitation(in)
0.00    83857
0.01     2003
0.02     1029
0.03      666
0.04      547
        ...
0.70        1
0.64        1
1.11        1
0.41        1
0.66        1
Name: count, Length: 88, dtype: int64
Weather_Condition
Fair                       38856
Cloudy                     18094
Mostly Cloudy              14777
Partly Cloudy               9908
Clear                       9387
                           ...
Drizzle and Fog                2
Light Snow Shower              1
Heavy Ice Pellets              1
Showers in the Vicinity        1
Squalls / Windy                1
Name: count, Length: 71, dtype: int64
Amenity
False    139397
True       1020
Name: count, dtype: int64
Bump
False    140383
True         34
Name: count, dtype: int64
Crossing
False    131378
True       9039
Name: count, dtype: int64
Give_Way
False    140060
True        357
Name: count, dtype: int64
Junction
False    123332
True      17085
Name: count, dtype: int64
No_Exit
False    140234
True        183
Name: count, dtype: int64
Railway
False    139815
True        602
Name: count, dtype: int64
Roundabout
False    140412
True          5
Name: count, dtype: int64
Station
False    138024
True       2393
Name: count, dtype: int64
Stop
False    138903
True       1514
Name: count, dtype: int64
Traffic_Calming
False    139953
True        464
Name: count, dtype: int64
Traffic_Signal
False    124509
True      15908
Name: count, dtype: int64
Turning_Loop
False    140417
Name: count, dtype: int64
Sunrise_Sunset
Day      93834
Night    46297
Name: count, dtype: int64
Civil_Twilight
Day      100731
Night     39400
Name: count, dtype: int64
Nautical_Twilight
Day      107877
Night     32254
Name: count, dtype: int64
Astronomical_Twilight
Day      113918
Night     26213
Name: count, dtype: int64

In [50]:
# Error checking of date time error I was getting over and over (One row had date and time recorded with higher
# granularity)
df.iloc[46456, :]

ID                                                               A-3710810
Source                                                             Source1
Severity                                                                 2
Start_Time                                             2022-05-12 23:39:31
End_Time                                               2022-05-13 00:54:33
Start_Lat                                                        38.804332
Start_Lng                                                       -76.906416
End_Lat                                                          38.804518
End_Lng                                                         -76.906239
Distance(mi)                                                         0.016
Description              Incident on ALLENTOWN RD near ALLENTOWN RD Dri...
Street                                                                 NaN
City                                                          Temple Hills
County                                                     Prince George's
State                                                                   MD
Zipcode                                                              20748
Country                                                                 US
Timezone                                                        US/Eastern
Airport_Code                                                          KWBC
Weather_Timestamp                                      2022-05-12 23:41:00
Temperature(F)                                                        63.0
Wind_Chill(F)                                                         63.0
Humidity(%)                                                          100.0
Pressure(in)                                                         29.91
Visibility(mi)                                                        10.0
Wind_Direction                                                           E
Wind_Speed(mph)                                                        8.0
Precipitation(in)                                                      0.0
Weather_Condition                                                   Cloudy
Amenity                                                              False
Bump                                                                 False
Crossing                                                              True
Give_Way                                                             False
Junction                                                             False
No_Exit                                                              False
Railway                                                              False
Roundabout                                                           False
Station                                                              False
Stop                                                                 False
Traffic_Calming                                                      False
Traffic_Signal                                                        True
Turning_Loop                                                         False
Sunrise_Sunset                                                       Night
Civil_Twilight                                                       Night
Nautical_Twilight                                                    Night
Astronomical_Twilight                                                Night
Name: 3683265, dtype: object

In [51]:
# Create year, month, and day columns out of date time
df['Year'], df['Month'], df['Day'] = df['Start_Time'].dt.year, df['Start_Time'].dt.month, df['Start_Time'].dt.day
df

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Year,Month,Day
228546,A-228553,Source2,2,2016-11-30 11:58:01,2016-11-30 16:57:20,39.152046,-76.645584,NaN,NaN,0.010,...,False,False,False,Day,Day,Day,Day,2016,11,30
228547,A-228554,Source2,3,2016-11-30 12:04:03,2016-11-30 17:02:36,39.152046,-76.645584,NaN,NaN,0.010,...,False,False,False,Day,Day,Day,Day,2016,11,30
228560,A-228567,Source2,2,2016-11-30 16:54:53,2016-11-30 17:24:12,39.481083,-76.249626,NaN,NaN,0.010,...,False,True,False,Night,Day,Day,Day,2016,11,30
228567,A-228574,Source2,2,2016-11-30 17:33:47,2016-11-30 18:01:49,39.158756,-76.718475,NaN,NaN,0.010,...,False,False,False,Night,Night,Day,Day,2016,11,30
228573,A-228580,Source2,2,2016-11-30 17:35:33,2016-11-30 18:05:10,39.636391,-77.710457,NaN,NaN,0.010,...,False,True,False,Night,Night,Day,Day,2016,11,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7727511,A-7776879,Source1,2,2019-08-22 19:48:26,2019-08-22 20:17:11,39.494560,-76.892370,39.49561,-76.89158,0.084,...,False,False,False,Day,Day,Day,Day,2019,8,22
7727512,A-7776880,Source1,2,2019-08-22 19:48:26,2019-08-22 20:17:11,39.495610,-76.891580,39.49456,-76.89237,0.084,...,False,True,False,Day,Day,Day,Day,2019,8,22
7727513,A-7776881,Source1,4,2019-08-22 19:57:25,2019-08-23 00:56:06,39.600500,-77.677230,39.60544,-77.73422,3.053,...,False,False,False,Night,Day,Day,Day,2019,8,22
7727996,A-7777364,Source1,2,2019-08-23 08:03:29,2019-08-23 08:32:31,39.336120,-76.491730,39.33962,-76.49409,0.273,...,False,False,False,Day,Day,Day,Day,2019,8,23
7728015,A-7777383,Source1,3,2019-08-23 17:03:55,2019-08-23 17:33:46,39.030140,-77.122970,39.03093,-77.12763,0.256,...,False,False,False,Day,Day,Day,Day,2019,8,23

In [52]:
def season(x):
    tomap = {1:"Winter",2:"Winter",3:"Spring",4:"Spring",5:"Spring",6:"Summer",7:"Summer",8:"Summer",9:"Fall",10:"Fall",11:"Fall",12:"Winter"}
    if x in tomap:
        return tomap[x]
    return x

In [53]:
df['Start_Time'] = pd.to_datetime(df['Start_Time'],format='mixed')
df['Month'] = df['Start_Time'].dt.month
df["Season"] = df.Month.apply(season)

In [54]:
# Convert street names to strings
df['Street'].astype(str)

228546              I-97 S
228547              I-97 S
228560     Philadelphia Rd
228567            MD-100 E
228573       E Antietam St
                ...
7727511          Gamber Rd
7727512           Emory Rd
7727513             I-70 W
7727996            I-695 N
7728015            I-270 N
Name: Street, Length: 140417, dtype: object

In [55]:
def street_type(x):
    if "Tunl" in x or "Tunnel" in x:
        return "Tunnel"#nsew(x,"Tunnel")
    if "I-" in x:
        return "Interstate"
    if " Dr " in x or " Ave " in x or " Rd " in x or " Xing" in x or " Way " in x:
        return "local"
    if "Beltway" in x:
        return "Beltway"
    if "US-" in x[:4] or "MD-" in x[:4] or "Expy" in x:
        return "Highway"
    if "Hwy" in x or "Fwy" in x or "Highway" in x or "Route" in x or "Connector" in x or "Byp" in x or "Bypass" in x or "Gtwy" in x or "Brg" in x or "Trwy" in x:
        return "Highway"
    if x[-2:] in ["St","Pl","Dr","Sq"]:
        return "local"
    if "Ln" in x or "Rd" in x or "Ct" in x:
        return "local"
    if x[-3:] in ["Way","Cir","Ter","Trl","Plz","Aly","Grn","way","Ext"]:
        return "local"
    if "Ave" in x[-5:] or " Blvd" in x or " Pike" in x or "Pkwy" in x or "Crse" in x or "Alameda" in x:
        return "large_local"
    if "Garth" in x or "Spell" in x or "Psge" in x or "Chase" in x or "Cutoff" in x or "Spire" in x:
        return "local"
    if "Overlook" in x or "Battlefield" in x or "Cemetery" in x or "Park" in x or "Base" in x or "Concourse" in x or "Memorial" in x:
        return "special"
    if "Loop" in x or "Greenway" in x or "West" in x or "ville" in x or "wood" in x:
        return "local"
    
    return x

In [56]:
df["Street"] = df["Street"].astype(str)
df["Street"] = df.Street.apply(street_type)

In [57]:
df=df.loc[~df.Street.str.contains("special")]

In [58]:
df.Street.value_counts()

Street
Interstate                            38841
local                                 34389
large_local                           24719
Highway                               24649
Beltway                               14316
                                      ...
Harriet Tubman Underground RR Bywy        1
4B                                        1
13C                                       1
 Fraternity Row                           1
US 50                                     1
Name: count, Length: 127, dtype: int64

In [59]:
# Proper formatting of county names (I took an educated guess that "Baltimore" referred to Balt. County and not City, this
# may not be correct)

def replace_misspelled(text):
    corrections = {'St Marys': "St. Mary's", 'Prince Georges': "Prince George's", 'Queen Annes': "Queen Anne's", 
                   "Baltimore (City)":"Baltimore City","Saint Marys":"St. Mary's", "Baltimore County":"Baltimore"}
    for word, correction in corrections.items():
        text = text.replace(word, correction)
    return text

df['County'] = df['County'].apply(replace_misspelled)

df["County"].value_counts(sort=True)

C:\Users\bkb3\AppData\Local\Temp\ipykernel_11136\1038882605.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['County'] = df['County'].apply(replace_misspelled)

County
Prince George's         27134
Montgomery              22565
Baltimore               22374
Frederick               13051
Anne Arundel            11947
Baltimore City          10210
Harford                  6802
Howard                   6132
Washington               4848
Cecil                    2482
Queen Anne's             2436
Charles                  2037
Carroll                  1360
Talbot                   1178
Worcester                1154
Caroline                  908
Allegany                  770
St. Mary's                658
Wicomico                  621
Dorchester                593
Garrett                   360
Kent                      328
Calvert                   223
Somerset                  216
District Of Columbia        4
Name: count, dtype: int64

In [60]:
# One hot function (Could not find the one line function Dr. Olsen referred to)
def onehotinator(df, string):
    one_hot = pd.get_dummies(df[string], prefix=string)
    one_hot = one_hot.astype(int)
    df = df.join(one_hot)
    df = df.drop(columns=string)
    return df

In [61]:
# Boolean column feature for if snowy OR icy conditions were present
lst = ['Snow', 'Freezing', 'Ice', 'Wintry', 'Hail', 'Sleet']
df['Snow_Ice']=np.where(df['Weather_Condition'].str.contains('|'.join(lst), na=False), True, False)

C:\Users\bkb3\AppData\Local\Temp\ipykernel_11136\46719036.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Snow_Ice']=np.where(df['Weather_Condition'].str.contains('|'.join(lst), na=False), True, False)

In [62]:
# Boolean column feature for if mist OR fog OR haze was present, OR if visibility in miles was less than 0.001 mi
lst = ['Fog', 'Mist', 'Haze', 'Heavy']
df['Low_Vis_Weather']=np.where((df['Weather_Condition'].str.contains('|'.join(lst), na=False) | df["Visibility(mi)"] < 0.001), True, False)

C:\Users\bkb3\AppData\Local\Temp\ipykernel_11136\2502039389.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Low_Vis_Weather']=np.where((df['Weather_Condition'].str.contains('|'.join(lst), na=False) | df["Visibility(mi)"] < 0.001), True, False)

In [63]:
# Boolean column feature for if road conditions were wet (weather was rain/storm related, OR there was more than 0 inches
# of precipitation at time of crash)
lst = ['Rain', 'Drizzle', 'Thunderstorm', 'T-Storm', 'Precipitation']
df['Rainy']=np.where((df['Weather_Condition'].str.contains('|'.join(lst), na=False) | df['Precipitation(in)'] >= 0.01), True, False)

C:\Users\bkb3\AppData\Local\Temp\ipykernel_11136\2542152748.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rainy']=np.where((df['Weather_Condition'].str.contains('|'.join(lst), na=False) | df['Precipitation(in)'] >= 0.01), True, False)

In [64]:
# Check which columns to delete
df.head()
df.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight', 'Year', 'Month', 'Day', 'Season', 'Snow_Ice',
       'Low_Vis_Weather', 'Rainy'],
      dtype='object')

In [65]:
# Remove all but one day/night column
# Col measures were: 
# Sun up/down based on the time of day
# Sun up/down based on street lights being needed or not
# Sun up/down based on being able to see the horizon at sea
# Sun up/down based on being able to see stars
df = df.drop(columns=['Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight', 'Weather_Condition'])
df.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Year', 'Month', 'Day', 'Season', 'Snow_Ice',
       'Low_Vis_Weather', 'Rainy'],
      dtype='object')

In [66]:
# Reference for data conversion
df.dtypes

ID                           object
Source                       object
Severity                      int64
Start_Time           datetime64[ns]
End_Time             datetime64[ns]
Start_Lat                   float64
Start_Lng                   float64
End_Lat                     float64
End_Lng                     float64
Distance(mi)                float64
Description                  object
Street                       object
City                         object
County                       object
State                        object
Zipcode                      object
Country                      object
Timezone                     object
Airport_Code                 object
Weather_Timestamp            object
Temperature(F)              float64
Wind_Chill(F)               float64
Humidity(%)                 float64
Pressure(in)                float64
Visibility(mi)              float64
Wind_Direction               object
Wind_Speed(mph)             float64
Precipitation(in)           float64
Amenity                        bool
Bump                           bool
Crossing                       bool
Give_Way                       bool
Junction                       bool
No_Exit                        bool
Railway                        bool
Roundabout                     bool
Station                        bool
Stop                           bool
Traffic_Calming                bool
Traffic_Signal                 bool
Turning_Loop                   bool
Sunrise_Sunset               object
Year                          int32
Month                         int32
Day                           int32
Season                       object
Snow_Ice                       bool
Low_Vis_Weather                bool
Rainy                          bool
dtype: object

In [67]:
# Convert all boolean columns to 1/0 integer columns and only day/night column to 1/0

bools = ['Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 
             'Traffic_Signal', 'Turning_Loop', 'Low_Vis_Weather', 'Snow_Ice', 'Rainy']

for i in bools:
    df = df.astype({i:int}) 
    
df['Sunrise_Sunset'] = df.Sunrise_Sunset.map({'Day':1,'Night':0}) 

df.dtypes

ID                           object
Source                       object
Severity                      int64
Start_Time           datetime64[ns]
End_Time             datetime64[ns]
Start_Lat                   float64
Start_Lng                   float64
End_Lat                     float64
End_Lng                     float64
Distance(mi)                float64
Description                  object
Street                       object
City                         object
County                       object
State                        object
Zipcode                      object
Country                      object
Timezone                     object
Airport_Code                 object
Weather_Timestamp            object
Temperature(F)              float64
Wind_Chill(F)               float64
Humidity(%)                 float64
Pressure(in)                float64
Visibility(mi)              float64
Wind_Direction               object
Wind_Speed(mph)             float64
Precipitation(in)           float64
Amenity                       int64
Bump                          int64
Crossing                      int64
Give_Way                      int64
Junction                      int64
No_Exit                       int64
Railway                       int64
Roundabout                    int64
Station                       int64
Stop                          int64
Traffic_Calming               int64
Traffic_Signal                int64
Turning_Loop                  int64
Sunrise_Sunset              float64
Year                          int32
Month                         int32
Day                           int32
Season                       object
Snow_Ice                      int64
Low_Vis_Weather               int64
Rainy                         int64
dtype: object

In [68]:
def slowdown_level(row):
    return sum([row['Bump'],row["Crossing"], \
    row["Give_Way"], row["Junction"], row["Railway"],  \
    row['Roundabout'], row["Stop"], row["Traffic_Calming"], \
    row["Traffic_Signal"], row["Turning_Loop"]])

df['Qty_Slowing_Elements'] = df.apply(slowdown_level, axis=1)

df['Qty_Slowing_Elements'].value_counts()

Qty_Slowing_Elements
0    102601
1     31061
2      6267
3       455
4         7
Name: count, dtype: int64

In [69]:
# Reference for what to do next
df.isnull().sum()

ID                          0
Source                      0
Severity                    0
Start_Time                  0
End_Time                    0
Start_Lat                   0
Start_Lng                   0
End_Lat                 41968
End_Lng                 41968
Distance(mi)                0
Description                 0
Street                      0
City                        9
County                      0
State                       0
Zipcode                   260
Country                     0
Timezone                  260
Airport_Code              327
Weather_Timestamp       13518
Temperature(F)          15711
Wind_Chill(F)           47587
Humidity(%)             15825
Pressure(in)            14526
Visibility(mi)          27454
Wind_Direction          20198
Wind_Speed(mph)         34293
Precipitation(in)       49479
Amenity                     0
Bump                        0
Crossing                    0
Give_Way                    0
Junction                    0
No_Exit                     0
Railway                     0
Roundabout                  0
Station                     0
Stop                        0
Traffic_Calming             0
Traffic_Signal              0
Turning_Loop                0
Sunrise_Sunset            286
Year                        0
Month                       0
Day                         0
Season                      0
Snow_Ice                    0
Low_Vis_Weather             0
Rainy                       0
Qty_Slowing_Elements        0
dtype: int64

In [70]:
# Reference for feature engineering ideas
max(df['Temperature(F)']), min(df['Temperature(F)'])

(100.9, 1.0)

In [71]:
# Reference for feature engineering ideas
df['Wind_Chill(F)'].value_counts(sort=True)

Wind_Chill(F)
 70.0    2204
 73.0    2144
 72.0    2093
 52.0    2012
 54.0    1910
         ...
 0.3        1
-4.0        1
 7.4        1
-6.9        1
 43.7       1
Name: count, Length: 517, dtype: int64

In [72]:
# Column for potentially freezing conditions if temp at accident time was below freezing OT windchill was below freezing
# OR if the previous column checking for snow and ice was true snow/ice present

def freezing(row):
   if (row["Temperature(F)"]<=32) | (row["Wind_Chill(F)"]<=32) | (row["Snow_Ice"] == 1):
      return 1
   else:
      return 0

df['Freezing'] = df.apply(freezing, axis=1)

df["Freezing"].value_counts()

Freezing
0    121402
1     18989
Name: count, dtype: int64

In [73]:
# Due to a technical ctrl+z error, I lost all instances of removing columns as I went, this is a quick fix (I didn't remember
# which columns were removed at which points)
df.isnull().sum()
df.columns

for col in df.columns:
    print(df[col].name, df[col].isnull().sum())

df = df.drop(columns=['ID','Source','Start_Time','End_Time','Start_Lat','Start_Lng','End_Lat','End_Lng','Weather_Timestamp',
           'Temperature(F)','Wind_Chill(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Direction',
           'Wind_Speed(mph)','Precipitation(in)','Description','Street','City','State','Zipcode','Country','Timezone',
           'Airport_Code'])

# Dropping remaining null values left

df = df.dropna(how='any')

df.isnull().sum()

ID 0
Source 0
Severity 0
Start_Time 0
End_Time 0
Start_Lat 0
Start_Lng 0
End_Lat 41968
End_Lng 41968
Distance(mi) 0
Description 0
Street 0
City 9
County 0
State 0
Zipcode 260
Country 0
Timezone 260
Airport_Code 327
Weather_Timestamp 13518
Temperature(F) 15711
Wind_Chill(F) 47587
Humidity(%) 15825
Pressure(in) 14526
Visibility(mi) 27454
Wind_Direction 20198
Wind_Speed(mph) 34293
Precipitation(in) 49479
Amenity 0
Bump 0
Crossing 0
Give_Way 0
Junction 0
No_Exit 0
Railway 0
Roundabout 0
Station 0
Stop 0
Traffic_Calming 0
Traffic_Signal 0
Turning_Loop 0
Sunrise_Sunset 286
Year 0
Month 0
Day 0
Season 0
Snow_Ice 0
Low_Vis_Weather 0
Rainy 0
Qty_Slowing_Elements 0
Freezing 0

Severity                0
Distance(mi)            0
County                  0
Amenity                 0
Bump                    0
Crossing                0
Give_Way                0
Junction                0
No_Exit                 0
Railway                 0
Roundabout              0
Station                 0
Stop                    0
Traffic_Calming         0
Traffic_Signal          0
Turning_Loop            0
Sunrise_Sunset          0
Year                    0
Month                   0
Day                     0
Season                  0
Snow_Ice                0
Low_Vis_Weather         0
Rainy                   0
Qty_Slowing_Elements    0
Freezing                0
dtype: int64

In [74]:

for col in df.columns:
    print(df[col].name, df[col].isnull().sum())

# Just to be safe, drop duplicates again
df = df.drop_duplicates()

Severity 0
Distance(mi) 0
County 0
Amenity 0
Bump 0
Crossing 0
Give_Way 0
Junction 0
No_Exit 0
Railway 0
Roundabout 0
Station 0
Stop 0
Traffic_Calming 0
Traffic_Signal 0
Turning_Loop 0
Sunrise_Sunset 0
Year 0
Month 0
Day 0
Season 0
Snow_Ice 0
Low_Vis_Weather 0
Rainy 0
Qty_Slowing_Elements 0
Freezing 0

In [75]:
df.shape
df.dtypes
# Somehow sun up/down col was a float, quick fix to be int
df["Sunrise_Sunset"]=df["Sunrise_Sunset"].astype(int)
df.dtypes
# Checked min and max of distance to decide on binning by hand or not
print(df['Distance(mi)'].min(),df['Distance(mi)'].max())

0.0 55.94600000000001

In [76]:
#df.to_csv('Fenrir_Feat_Eng.csv', index=False)

In [77]:
# Reference for thinking about CFD based division (We have 4 classes, and CFD only takes 2 at a time)
df['Severity'].value_counts()

Severity
2    86041
3    20479
4     9315
1      409
Name: count, dtype: int64

In [78]:
df.columns

Index(['Severity', 'Distance(mi)', 'County', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Year', 'Month', 'Day', 'Season', 'Snow_Ice',
       'Low_Vis_Weather', 'Rainy', 'Qty_Slowing_Elements', 'Freezing'],
      dtype='object')

In [81]:
def feat_eng_class_merge(df, c1, c2, c3, c4):
    df['Severity'] = df['Severity'].replace(c1, 0)
    df['Severity'] = df['Severity'].replace([c2, c3, c4], 1)
    df_c1 = df[df.Severity != 1]
    df_c2 = df[df.Severity != 0]
    df_c1.to_csv(f"feat_eng_class{c1}.csv", index = False)
    df_c2.to_csv(f"feat_eng_class{c2}_{c3}_{c4}_merge.csv", index = False)
    
    df['Severity'] = df['Severity'].replace(c2, 0)
    df['Severity'] = df['Severity'].replace([c1, c3, c4], 1)
    df_c1 = df[df.Severity != 1]
    df_c2 = df[df.Severity != 0]
    df_c1.to_csv(f"feat_eng_class{c2}.csv", index = False)
    df_c2.to_csv(f"feat_eng_class{c1}_{c3}_{c4}_merge.csv", index = False)
    
    df['Severity'] = df['Severity'].replace(c3, 0)
    df['Severity'] = df['Severity'].replace([c2, c1, c4], 1)
    df_c1 = df[df.Severity != 1]
    df_c2 = df[df.Severity != 0]
    df_c1.to_csv(f"feat_eng_class{c3}.csv", index = False)
    df_c2.to_csv(f"feat_eng_class{c2}_{c1}_{c4}_merge.csv", index = False)
    
    df['Severity'] = df['Severity'].replace(c4, 0)
    df['Severity'] = df['Severity'].replace([c2, c3, c1], 1)
    df_c1 = df[df.Severity != 1]
    df_c2 = df[df.Severity != 0]
    df_c1.to_csv(f"feat_eng_class{c4}.csv", index = False)
    df_c2.to_csv(f"feat_eng_class{c2}_{c3}_{c1}_merge.csv", index = False)

In [82]:
feat_eng_class_merge(df, 1, 2, 3, 4)

In [ ]:
def control_class_merge(df, c1, c2, c3, c4):
    df['Severity'] = df['Severity'].replace(c1, 0)
    df['Severity'] = df['Severity'].replace([c2, c3, c4], 1)
    df_c1 = df[df.Severity != 1]
    df_c2 = df[df.Severity != 0]
    df_c1.to_csv(f"control_class{c1}.csv", index = False)
    df_c2.to_csv(f"control_class{c2}_{c3}_{c4}_merge.csv", index = False)
    
    df['Severity'] = df['Severity'].replace(c2, 0)
    df['Severity'] = df['Severity'].replace([c1, c3, c4], 1)
    df_c1 = df[df.Severity != 1]
    df_c2 = df[df.Severity != 0]
    df_c1.to_csv(f"control_class{c2}.csv", index = False)
    df_c2.to_csv(f"control_class{c1}_{c3}_{c4}_merge.csv", index = False)
    
    df['Severity'] = df['Severity'].replace(c3, 0)
    df['Severity'] = df['Severity'].replace([c2, c1, c4], 1)
    df_c1 = df[df.Severity != 1]
    df_c2 = df[df.Severity != 0]
    df_c1.to_csv(f"control_class{c3}.csv", index = False)
    df_c2.to_csv(f"control_class{c2}_{c1}_{c4}_merge.csv", index = False)
    
    df['Severity'] = df['Severity'].replace(c4, 0)
    df['Severity'] = df['Severity'].replace([c2, c3, c1], 1)
    df_c1 = df[df.Severity != 1]
    df_c2 = df[df.Severity != 0]
    df_c1.to_csv(f"control_class{c4}.csv", index = False)
    df_c2.to_csv(f"control_class{c2}_{c3}_{c1}_merge.csv", index = False)